/*
 * JPanelMainWindow.java
 *
 * Created on August 28th, 2007
 * Revised on March 2nd, 2020
 */

package window;

import games.Game;
import games.IPDNet.GameIPDNet;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JPanel;



/**
 *
 * @author  JC
 */
public class JPanelMainWindow extends javax.swing.JPanel implements WindowCONS {

MainWindow oMainWindow;
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JButton oJButtonSetup;
private javax.swing.JButton oJButtonStep;
private javax.swing.JButton oJButtonMaxWindow;

private javax.swing.JPanel oVerticalPanel;

private javax.swing.JLabel oJLabelSimulation;
private javax.swing.JLabel oJLabelWorld;
private javax.swing.JLabel oJLabelInformation;

private static javax.swing.JButton oJButtonView1;
private static javax.swing.JButton oJButtonView2;
private static javax.swing.JButton oJButtonView3;
private static javax.swing.JButton oJButtonView4;
private static javax.swing.JButton oJButtonSOM;

//static javax.swing.JLabel oJLabelGame;
static javax.swing.JButton oJButtonGoStop;

static javax.swing.JLabel oJLabelNet;
static javax.swing.JLabel oJLabelBreakPoint;

static WorldGrid oWorldGrid;

//public static javax.swing.JLabel oJLabelChange;
public static javax.swing.JLabel oJLabelStatusData;

public static javax.swing.JLabel oJLabelPm;
public static javax.swing.JLabel oJLabelPn;
public static javax.swing.JLabel oJLabelPe;
public static javax.swing.JLabel oJLabelGames;


  // End of variables declaration//GEN-END:variables

  
/**
 * Creates new form JPanelMainWindow
 */
public JPanelMainWindow (MainWindow oVentAux) {
	oMainWindow = oVentAux;
  vInitComponents();
}



public static void vActivateButtons () {
	oJButtonView1.setText ("Basic Strats");
  oJButtonView1.setEnabled (true);
  oJButtonView2.setText ("Probs(1..4)");
  oJButtonView2.setEnabled (true);
  oJButtonView3.setText ("ZD Strats");
  oJButtonView3.setEnabled (true);
  oJButtonView4.setText ("P(C) >= 0.5");
  oJButtonView4.setEnabled (true);
  oJButtonSOM.setText ("SOM");
  oJButtonSOM.setEnabled (true);
 
  JPanelMainWindow.oWorldGrid.repaint();
}



/** This method is called from within the constructor to
 * initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is
 * always regenerated by the Form Editor.
 * oVisorWorld = new VisorWorld(oMainWindow);
 */
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void vInitComponents() {

  oVerticalPanel = new javax.swing.JPanel();
  oJButtonSetup = new javax.swing.JButton();
  oJButtonGoStop = new javax.swing.JButton();
  oJButtonMaxWindow = new javax.swing.JButton();
  oJButtonMaxWindow.setEnabled (false);
  oJButtonStep = new javax.swing.JButton();
          
  oJButtonView1 = new javax.swing.JButton();
  oJButtonView1.setOpaque(true);
  oJButtonView1.setBackground(Color.darkGray);
  
  oJButtonView2 = new javax.swing.JButton();
  oJButtonView2.setOpaque(false);
  oJButtonView2.setBackground(Color.darkGray);
  
  oJButtonView3 = new javax.swing.JButton();
  oJButtonView3.setOpaque(false);
  oJButtonView3.setBackground(Color.darkGray);
  
  oJButtonView4 = new javax.swing.JButton();
  oJButtonView4.setOpaque(false);
  oJButtonView4.setBackground(Color.darkGray);
  
  oJButtonSOM = new javax.swing.JButton();
  oJButtonSOM.setOpaque(false);
  oJButtonSOM.setBackground(Color.darkGray);
  
  oJLabelSimulation = new javax.swing.JLabel();
  oJLabelWorld = new javax.swing.JLabel();
  oJLabelInformation = new javax.swing.JLabel();
//  oJLabelGame = new javax.swing.JLabel();
//  oJLabelChange = new javax.swing.JLabel();
  oJLabelPm = new javax.swing.JLabel();
  oJLabelPn = new javax.swing.JLabel();
  oJLabelPe = new javax.swing.JLabel();
  oJLabelNet = new javax.swing.JLabel();
  oJLabelGames = new javax.swing.JLabel();
  oJLabelBreakPoint = new javax.swing.JLabel();
  
  
  oJLabelStatusData = new javax.swing.JLabel();

  setBorder(new javax.swing.border.MatteBorder(null));

  oJButtonSetup.setText("Setup");
  oJButtonSetup.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
          vSetupButActionPerformed(evt);
      }
  });

  oJButtonGoStop.setText("GO");
  oJButtonGoStop.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
          vGoStopButActionPerformed(evt);
      }
  });

  oJButtonStep.setText("Step");
  oJButtonStep.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
          vStepButActionPerformed(evt);
      }
  });

  oJButtonMaxWindow.setText("");
  oJButtonMaxWindow.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
          oMaxWindowButActionPerformed(evt);
      }
  });

  oJButtonView1.setText("Basic Strats");
  oJButtonView1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
          vButView1ActionPerformed(evt);
      }
  });

  oJButtonView2.setText("Probs(1..4)");
  oJButtonView2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
          vButView2ActionPerformed(evt);
      }
  });

  oJButtonView3.setText("ZD Strat");
  oJButtonView3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
          vButView3ActionPerformed(evt);
      }
  });

  oJButtonView4.setText("P(C) >= 0.5");
  oJButtonView4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
          vButView4ActionPerformed(evt);
      }
  
  });

	oJButtonSOM.setText("SOM");
	oJButtonSOM.addActionListener(new java.awt.event.ActionListener() {
		  public void actionPerformed(java.awt.event.ActionEvent evt) {
		      vButSOMActionPerformed(evt);
		  		}
  });

  oJLabelSimulation.setFont(new java.awt.Font("Tahoma", 1, 13));
  oJLabelSimulation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  oJLabelSimulation.setText("Simulation");
  
  oJLabelWorld.setFont(new java.awt.Font("Tahoma", 1, 13));
  oJLabelWorld.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  oJLabelWorld.setText("Grid View");
  
  oJLabelInformation.setFont(new java.awt.Font("Tahoma", 1, 13));
  oJLabelInformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  oJLabelInformation.setText("Information");
  
//  oJLabelGame.setText("Game:");
//  oJLabelChange.setText("Change:");
  oJLabelPm.setText("Pm:");
  oJLabelPn.setText("Pn:");
  oJLabelPe.setText("Pe:");
  oJLabelNet.setText("Net:");
  oJLabelGames.setText("Games:");
  oJLabelBreakPoint.setText("#GenStop:");
  
  

  
  //oJLabelStatusData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
  oJLabelStatusData.setFont(new java.awt.Font("Tahoma", 1, 13));
  oJLabelStatusData.setText("");
  
  oWorldGrid = new WorldGrid (oMainWindow);
  oWorldGrid.setBackground (new java.awt.Color(236, 233, 216));

  
  

//###################### BORDER LAYOUT ######################
  
	setLayout (new BorderLayout());

	JLabel oJLabel = new JLabel("");
  oJLabel.setPreferredSize(new Dimension (0,0));
  add(oJLabel, BorderLayout.PAGE_START);

  oVerticalPanel = new JPanel();						// Left panel for buttons and info.
  oVerticalPanel.setLayout (new GridLayout (19,1));
  oVerticalPanel.setBorder(BorderFactory.createEmptyBorder(5,5,5,5));

  oVerticalPanel.add(oJLabelSimulation);
  oVerticalPanel.add(oJButtonSetup);
  oVerticalPanel.add(oJButtonGoStop);
  oVerticalPanel.add(oJButtonStep);
  oVerticalPanel.add(Box.createRigidArea(new Dimension(0, 40)));
  
  oVerticalPanel.add(oJLabelWorld);
  oVerticalPanel.add(oJButtonView1);
  oVerticalPanel.add(oJButtonView2);
  oVerticalPanel.add(oJButtonView3);
  oVerticalPanel.add(oJButtonView4);
  oVerticalPanel.add(oJButtonSOM);
  oVerticalPanel.add(Box.createRigidArea(new Dimension(0, 40)));
  
  oVerticalPanel.add(oJLabelInformation);
//  oVerticalPanel.add(oJLabelGame);
//  oVerticalPanel.add(oJLabelChange);
  oVerticalPanel.add(oJLabelPm);
  oVerticalPanel.add(oJLabelPn);
  oVerticalPanel.add(oJLabelPe);
  oVerticalPanel.add(oJLabelNet);
  oVerticalPanel.add(oJLabelGames);
  oVerticalPanel.add(oJLabelBreakPoint);
  
  add(oVerticalPanel, BorderLayout.LINE_START);

  
  //Make the center component big (typical usage of BorderLayout)
  add(oWorldGrid, BorderLayout.CENTER);

  add(oJLabel, BorderLayout.LINE_END);

  oJLabelStatusData.setPreferredSize(new Dimension (25,25));
  add(oJLabelStatusData, BorderLayout.PAGE_END);

  
//###################### BORDER LAYOUT ######################  

  
}// </editor-fold>//GEN-END:initComponents

    
    
private void vSetupButActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oSetupButActionPerformed
  oMainWindow.vSetupThread();
}//GEN-LAST:event_oSetupButActionPerformed
    
private void vGoStopButActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oContButActionPerformed
  if (oJButtonGoStop.getText().equals("GO"))
    oMainWindow.vGoThread();
  else
    oMainWindow.vStopThread();
}//GEN-LAST:event_oContButActionPerformed

private void vStepButActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oStepButActionPerformed
  oMainWindow.vStepThread();
}//GEN-LAST:event_oStepButActionPerformed



private void oMaxWindowButActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oStepButActionPerformed

}//GEN-LAST:event_oStepButActionPerformed



private void vButView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oCellsButActionPerformed
  Game.iWorldShow = iWORLD_SHOW_BASIC_STRATS;
  vRemarkButton();
  JPanelMainWindow.oWorldGrid.repaint();
}//GEN-LAST:event_oCellsButActionPerformed


private void vButView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oProfitButActionPerformed
  Game.iWorldShow = iWORLD_SHOW_PROBS;
  vRemarkButton();
  JPanelMainWindow.oWorldGrid.repaint();
}//GEN-LAST:event_oProfitButActionPerformed


private void vButView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oSolutionsButActionPerformed 
	Game.iWorldShow = iWORLD_SHOW_ZD_STRATS;
	vRemarkButton();
	JPanelMainWindow.oWorldGrid.repaint();
}//GEN-LAST:event_oSolutionsButActionPerformed


private void vButView4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oStratButActionPerformed
  Game.iWorldShow = iWORLD_SHOW_PROB_C;
  vRemarkButton();
  JPanelMainWindow.oWorldGrid.repaint();
}//GEN-LAST:event_oStratButActionPerformed


private void vButSOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oStratButActionPerformed
	Game.iWorldShow = iWORLD_SHOW_SOM;
  vRemarkButton();
  JPanelMainWindow.oWorldGrid.repaint();
}//GEN-LAST:event_oStratButActionPerformed



private void vRemarkButton () {
	oJButtonView1.setOpaque(false);
	oJButtonView2.setOpaque(false);
	oJButtonView3.setOpaque(false);
	oJButtonView4.setOpaque(false);
	oJButtonSOM.setOpaque(false);
	
	switch (Game.iWorldShow) {
		case 0: oJButtonView1.setOpaque(true); break;
		case 1: oJButtonView2.setOpaque(true); break;
		case 2: oJButtonView3.setOpaque(true); break;
		case 3: oJButtonView4.setOpaque(true); break;
		case 4: oJButtonSOM.setOpaque(true); break;
	}
	
	oJButtonView1.repaint();
	oJButtonView2.repaint();
	oJButtonView3.repaint();
	oJButtonView4.repaint();
	oJButtonSOM.repaint();
}


}
